services:
  - type: web
    name: gemini-audio-chatbot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
    plan: free